# Generated by Django 3.0.4 on 2020-03-22 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readingmanager', '0003_summary_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summary',
            options={'verbose_name_plural': 'summaries'},
        ),
        migrations.RenameField(
            model_name='summary',
            old_name='End Page',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='summary',
            old_name='Start Page',
            new_name='start',
        ),
    ]
